audit_header: false
title: Mortgage Video Blog with Jeff Van Nostran
description: Our mission at Jeff Van Nostran Team is to be your best resource for Mortgage advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about Mortgages. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Jeff Van Nostran Team.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Jeff Van Nostran
  title:
  license_number: 'NMLS: 757532'
  about_markdown: |
    Whether you're buying, selling, refinancing, or building your dream home, you have a lot riding on your loan officer. Since market conditions and mortgage programs change frequently, you need to make sure you're dealing with a top professional who is able to give you quick and accurate financial advice. As an experienced loan officer I have the knowledge and expertise you need to explore the many financing options available. Ensuring that you make the right choice for you and your family is my ultimate goal, and I am committed to providing my customers with mortgage services that exceed their expectations. I hope you'll browse my website, check out the different loan programs I have available, use my decision-making tools and calculators, and use our secure online application to get started. After you've applied, I'll call you to discuss the details of your loan, or you may choose to set up an appointment with me using my online form. As always, you may contact me anytime by phone, fax or email for personalized service and expert advice. I look forward to working with you.
  brand: Jeff Van Nostran Team
  brokerage: Movement Mortgage
  market: Seattle and California
  address: 27401 Los Altos Suite 410, Mission Viejo, CA 92691
  phone: 206-775-5693
  phone_type:
  phone2:
  phone2_type:
  email: jeff.vannostran@movement.com
  url: https://movement.com/lo/jeff-vannostran

CTAs:
  first_CTA_text: Apply Now
  first_CTA_URL: https://apply.movement.com/#/journey?referrerId=jeff.vannostran%40movement.com
  second_CTA_text: Contact Me
  second_CTA_URL: https://movement.com/lo/jeff-vannostran/#contact-form

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Quick, Easy Loan Application"
    CTA_text: "Let us help you get into your dream home. Get pre-approved online."
    CTA_link_text: "Apply Now"
    CTA_url: https://apply.movement.com/#/journey?referrerId=jeff.vannostran%40movement.com

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Questions? Want more information?"
    CTA_text2: "I would love to hear from you and be able to help."
    CTA_link_text2: "Contact Me"
    CTA_url2: https://movement.com/lo/jeff-vannostran/#contact-form

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/MovementMortgage
  linkedin_url: https://www.linkedin.com/company/movementmortgage
  youtube_url:
  twitter_url: https://twitter.com/MovementMtg
  instagram_url: https://www.instagram.com/movementmtg/
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Mortgage Podcast with Jeff Van Nostran'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Jeff Van Nostran Team.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer, Mortage, Mortgage loan, loan officer, seattle mortgage, california mortgage'
  author: 'Jeff Van Nostran'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: Mortgage Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#c7202f'
  theme_color: '#2d2a26'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#c7202f'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
